###
# This is the place to override the php cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "php/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

['php']['upload_max_filesize'] = 20M
['php']['post_max_size'] = 20M
