###
# This is the place to override the php cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "php/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###


node.set['php']['directives'] = { :upload_max_filesize => '20M' }
node.set['php']['directives'] = { :post_max_size => '20M' }